spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/review_app
    username: postgres
    password: qnocks
    driver-class-name: org.postgresql.Driver

  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
          indexBase: /lucene/index/default

app:
  jwt:
    secret: secretKey
    expiration-time: 600000
