spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/review_app}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qnocks}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
          indexBase: /lucene/index/default

app:
  jwt:
    secret: ${jwtSecret}
    expiration-time: 2400000

  cloudinary:
    cloud-name: ${cloudinary.cloudName}
    api-key: ${cloudinary.apiKey}
    api-secret: ${cloudinary.apiSecret}