spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  jwt:
    secret: secretKey
    expiration-time: 231312

  #spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/review_app
  #    username: postgres
  #    password: qnocks
  #    driver-class-name: org.postgresql.Drive
